package game.action;

/**
 * The different types of action a user can perform.
 * 
 * @author Callum
 */
public enum ActionType {
	/** Generated by pressing the 'W' key. */
	BEGIN_MOVE_NORTH,
	/** Generated by releasing the 'W' key. */
	END_MOVE_NORTH,
	/** Generated by pressing the 'S' key. */
	BEGIN_MOVE_SOUTH,
	/** Generated by releasing the 'S' key. */
	END_MOVE_SOUTH,
	/** Generated by pressing the 'D' key. */
	BEGIN_MOVE_EAST,
	/** Generated by releasing the 'D' key. */
	END_MOVE_EAST,
	/** Generated by pressing the 'A' key. */
	BEGIN_MOVE_WEST,
	/** Generated by releasing the 'A' key. */
	END_MOVE_WEST,
	/** Generated by moving the mouse. */
	AIM,
	/** Generated by pressing mouse button 1 down. */
	BEGIN_USE,
	/** Generated by releasing mouse button 1. */
	END_USE,
	/** Generated by pressing the 'E' key. */
	PICKUP,
	/** Generated by pressing the 'T' key. */
	TOGGLE_LIGHT(true);
	
	ActionType() {
		this.tcp = false;
	}
	ActionType(boolean tcp) {
		this.tcp = tcp;
	}
	
	private boolean tcp;
	
	public boolean isTcp() {
		return tcp;
	}
}
