matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
language: java
before_install:
    - wget http://services.gradle.org/distributions/gradle-3.2-bin.zip
    - unzip gradle-3.2-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.2
    - export PATH=$PATH:$GRADLE_HOME/bin
script: mvn clean install -Dmaven.javadoc.skip=false
